# Generated by Django 2.0.1 on 2018-01-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portchecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portsstatus',
            name='port_type',
            field=models.CharField(default='TCP', max_length=3),
        ),
        migrations.AlterField(
            model_name='portsstatus',
            name='port_name',
            field=models.CharField(max_length=26),
        ),
    ]
